# Generated by Django 2.2.2 on 2020-07-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzaname', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
    ]
