# Generated by Django 2.2.2 on 2020-07-10 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_customermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='confirm_password',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
