# Generated by Django 2.2.2 on 2020-07-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0004_ordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='user_id',
            new_name='userid',
        ),
        migrations.AlterField(
            model_name='customermodel',
            name='confirm_password',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(max_length=100),
        ),
    ]
