# Generated by Django 2.2.2 on 2020-07-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0005_auto_20200714_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='orders_status',
            field=models.CharField(default='Pending', max_length=10),
            preserve_default=False,
        ),
    ]
